name: Build v10.26

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Patch Containerfile (fix 404 bullseye-backports)
        run: sed -i 's|bullseye-backports|bookworm-slim|' build.Containerfile

      - name: Cài buildah
        run: sudo apt-get update && sudo apt-get install -y buildah fuse-overlayfs

      - name: Build
        run: |
          mkdir out
          sudo buildah build --cap-add SYS_ADMIN --device /dev/fuse \
            --file build.Containerfile --output out .

      - uses: actions/upload-artifact@v4
        with:
          name: v10.26
          path: out/*.apk